### ISSUE TITLE
Mame cores in final burn neo

### ISSUE THREAD

**Issue by SegAgeS** [TapiocaFox/Daijishou#442]
Can mame cores be added to the fbneo pack.  Altered beast requires the MAME 2003 core.

I am aware its available within the mame platform but it isnt showing in the fbneo pack that ive installed

**Comment by Post-Mortem** [comment]
I got altered beat in my fbneo collection. I use non merged roms, that way I can download my games individually, each in a separate zip file. If you dm me in discord i can help you with that. Join the daijisho discord server and find me (post mortem.)

I'm closing this because this is not a Daijisho issue.
