### ISSUE TITLE
Add option to select emulator (like Retroid Launcher) (Sorry, meant "Add emulator not in the current list for systems")

### ISSUE THREAD

**Issue by phalkon13** [TapiocaFox/Daijishou#486]
Like the title says, if there's a way to change the default emulator for a system, I cannot find documentation for it.
Example: Currently, I cannot get 3DO working with RetroArch, but it works perfectly with "Real3DOPlayer" (freeware version, not on Play store).  I would like to change the default emulator on the Daijushou front-end to use Real3DOPlayer, but I do not see any documentation or easily accessability to do so.

If I am mistaken, please link more information on here, and it would be very helpful to link such documentation in the Daijishou setup docs as well.

Thanks!

**Comment by Jetup13** [comment]
You can select & change emulators 

> Highlight Platform > 🖊️ > Player Settings > select emulator from default player dropdown > save

Real3DOPlayer is not added to the 3DO players. Let me check if it supports loading from a front-end. If it does I'll add it to the list.

**Comment by phalkon13** [comment]
Let me know if you need a link for the app, since it's not on Play store anymore)

**Comment by Jetup13** [comment]
I was able to launch a game from the app but not from a frontend. I assume its because its not passing bios along with the game. 

This is what I used:

```
  -n ru.vastness.altmer.real3doplayer/.MainActivity
  -a android.intent.action.VIEW
  -e cd "{file.path}"
  --activity-clear-task
  --activity-clear-top
  --activity-no-history
```
Used real3DOPlayer_free_1.0.32

Same goes with RetroidLauncher, could not launch it. There's no information on other parameters that can be used.

We're you able to launch it from RetroidLauncher? 

You can try adding it yourself by:

> Daijishou > Settings > Library > Add a player

Input player name

Player am start should be the one posted above

Player accepted file name regex: 

```
^(.*)\.(?:cue|bin|iso)$
```

**Comment by Jetup13** [comment]
Closing issue as the emulator in question hasn't been updated in awhile and seems like it will not. There's a [3DO emulator](https://github.com/TapiocaFox/Daijishou/wiki/Players-and-File-Extensions#3do-interactive-multiplayer) on RetroArch that work fine as long as BIOS are present as noted in the wiki and Libretro docs
