### ISSUE TITLE
Problem launching Redream

### ISSUE THREAD

**Issue by GreatAsaf** [TapiocaFox/Daijishou#487]
I would like to leave the following error with Daijisho, Android 13 and the Google Play version: Unable to find explicit activity class Main Activity.

This happens wherever redream io.recompiled.redream) is set as custom emulator for a given rom.

If retroArch or flycast is set, there is no problem launching.  Iolen, the redream dev, said the following: "Sounds like an error on their end? As Andrew is showing, we can launch the main activity, but for some reason with saf paths it's going off the rails."

**Comment by Jetup13** [comment]
Wonder if its a similar problem [PPSSPP](https://github.com/hrydgard/ppsspp/issues/17416) had when they updated with SAF. 

Right now the redream player is currently set:

```
-n io.recompiled.redream/.MainActivity
  -a android.intent.action.VIEW
  -d {file.path}
```

file.path is most likely wrong and needs to be set file.uri as Redream might use URI paths now. Try changing it and see if anything different happens

> Daijishou > Settings > Library > inspect players > select `dreamcast - io.recompiled.redream` edit {file.path} to {file.uri}.

**Comment by Jetup13** [comment]
I've [updated](https://github.com/TapiocaFox/Daijishou/commit/bfbdd48cf5d0196aeeacb8a0bc8f1ae9fddc64da) the launch arguments for Redream in both Atomiswave and Dreamcast platform. Seems the problem was both the launch arguments being set to file.path & something within Redreams side.

Update Redream to latest. 

Also update the platforms on Daijishou for the fixed launch arguments

> Daijishou > Settings > Library > Update platforms automatically

Or 

> Download > Dreamcast & Atomiswave > Import

**Comment by aebrae** [comment]
it still doesnt work after I change file.path to file.uri  

Any other suggestions? Redream and Daijisho are updated from Play Store.
