### ISSUE TITLE
Intellivision.json - 7z files for freeintv

### ISSUE THREAD

**Issue by feeltheburn** [TapiocaFox/Daijishou#503]
The freeintv core info for retroarch doesn't state it, but 7z files work with it. I can run them with no problem.

Can't get them to list in Daijishou though.

It's not like I saved much space so I just uncompressed them to get them to list. But 7z should be accepted.

**Comment by EgoBizarro** [comment]
It's not the core that has 7z support, but RetroArch itself, no matter what core.

**Comment by feeltheburn** [comment]
Eh, okay. Regardless, 7z works in RetroArch with the freeintv core, so the games should list in Dai as well.

**Comment by EgoBizarro** [comment]
Well, I guess zip and 7z could be extensions for all platforms with non-disc-based roms. Actually, I never understood why there's even the need to narrow down extensions for each platform.

**Comment by Jetup13** [comment]
I've been going through platforms the past few days and cleaning/fixing some missed file extensions. Just haven't pushed the changes yet. Adding 7z will be apart of it.

@EgoBizarro the reason why you'll want to narrow down file extensions is because not every file can actually be launched or might have problems launching.

For instance CD based platforms that use bin/cue. Sure some emulators can launch just the bin but for games that are multitrack you'll have a problem with audio. So what we do is omit the bin file from being looked at entirely. This will make the user load the cue file thus preventing the possible problem.

**Comment by EgoBizarro** [comment]
But wouldn't it be a lot less work not to include but to exclude file types, e.g. bin in disc-based platforms. I can't think of many other examples like that.

**Comment by Jetup13** [comment]
Scummvm, Arcade, PC, & few others would be a pain. Plus regex is already used twice to include or exclude, user can edit either if they desire. One is global while the other is per player

Global:

> Daijishou > Settings > Inspect platform > Accepted filename regex

Player:

> Daijishou > Settings > Inspect player > Accepted filename regex

You can use this in ways where one player might not have as many supported file extensions as another. Sounds like a headache at first but it works.

**Comment by Jetup13** [comment]
Updated the platforms to include both zip & 7z in [1b76a88](https://github.com/TapiocaFox/Daijishou/commit/1b76a889871db4ced0ac300ba7433b0f6fbb6a83)

Please update your platforms:

> Daijishou > Settings > Library > Update platforms automatically

Or

> Download > Select platform

There's still more platforms I have to clean up. Closing this issue for now
