### ISSUE TITLE
Cannot scan zipped 3ds roms

### ISSUE THREAD

**Issue by kid1412621** [TapiocaFox/Daijishou#576]
But Sega master system roms can be found

**Comment by Jetup13** [comment]
[Here's a list of file extensions that can be found in the 3DS platform](https://github.com/TapiocaFox/Daijishou/wiki/Players-and-File-Extensions#nintendo-3ds). As you notice zipped formats are missing. Simply unzip your 3ds roms and scrape again

**Comment by sammcj** [comment]
Yeah I'd call this a bug, most emulators operate on zipped roms, if it wasn't for that you'd use a LOT more storage space up.

**Comment by Jetup13** [comment]
It's not a bug, zip was not included in the regex as it's not supported in Citra. It only works through RetroArch because RetroArch temporarily extracts the file. 

You can edit the regex to include zip

[Edit Players](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#edit-players)
